### ISSUE TITLE
Manage Locations

### ISSUE THREAD

**Issue by tandyman** [strangerstudios/pmpro-nav-menus#1]
Additional menus don't show in manage locations section. Even after selecting "Check this if you want to create unique navigation menus for this level."

**Comment by jcaruso001** [comment]
Mine either.

**Comment by meta4creations** [comment]
I just ran into this same issue. It's because the plugin is hooked into the "init" action without a low priority. Unless your menu is registered on init with a specific priority higher than 10, the plugin attempts to duplicate your menus before your menus have actually registered.

I'll attempt to make a pull request and get them to set a low priority on their hook.
